### ISSUE TITLE
`next-image-snapshot`: Debug mode

### ISSUE THREAD

**Issue by kdy1** [dudykr/js-utils#6]
```[tasklist]
### Tasks
- [ ] https://github.com/dudykr/js-utils/issues/13
- [ ] https://github.com/dudykr/js-utils/issues/14
- [ ] https://github.com/dudykr/js-utils/issues/15
```
